### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by okadarenta** [okadarenta/furima-39680#20]
自身のフリマアプリのURL https://furima-39680.onrender.com/
Basic認証のIDとパスワード admin  2222
出品者用のメールアドレスとパスワード test11@test.com   pass1122
購入者用のメールアドレスとパスワード test1122@test.com   pass1122

**Comment by snkw-works** [comment]
@okadarenta さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
#### 商品出品機能
- [x] **商品の状態は、「---、新品・未使用、未使用に近い、目立った傷や汚れなし、やや傷や汚れあり、傷や汚れあり、全体的に状態が悪い」の7項目が表示されるよう修正しましょう**
「新品・未使用」が分かれて表示されています。
![スクリーンショット_2023-09-13_17_53_46](https://github.com/okadarenta/furima-39680/assets/54050089/3915095a-4a0b-4a93-bd5b-fd2ecf60ee42)

- [x] **入力された販売価格によって、販売手数料や販売利益が変わるよう修正しましょう(JavaScriptを使用して実装すること)**
一度出品に失敗しエラーが出た後でないと、販売手数料と販売利益が表示されません。どの段階でも入力したら表示されるよう修正しましょう。

#### 商品購入機能
- [x] **商品購入ページにて、クレジットカードの情報が入力できるよう修正しましょう**
エラーを発生させた後の購入画面で、クレジットカードの情報入力欄は表示されていますが、カーソルを合わせても入力ができない状態です。

https://github.com/okadarenta/furima-39680/assets/54050089/43a945c1-f231-4580-bda9-2fe310e094ed

※補足
トップページの「人生を変えるフリマアプリ」の背景画像が表示されておりません。
こちらは必須要件ではございませんが、修正して頂くことでより完成度の高いアプリになります。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by okadarenta** [comment]
修正いたしました。
挙動確認は一度商品を出品し、購入画面で打てるのを確認してから商品削除を行っております。

**Comment by mo1015** [comment]
@okadarenta さん、再提出ありがとうございます‼︎
動作の確認をしたところ、引き続き修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **入力された販売価格によって、販売手数料や販売利益が変わるよう修正しましょう(JavaScriptを使用して実装すること)**
今回は、一度出品に失敗し**エラーが出た後に再度価格を入力すると、**販売手数料と販売利益が表示されなくなってしまいました。どの段階でも入力したら表示されるよう修正しましょう。

- [ ] **商品購入ページにて、クレジットカードの情報が入力できるよう修正しましょう**
前回同様、一度購入に失敗しエラーを発生させた後の購入画面で入力ができない状態です。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by okadarenta** [comment]
修正いたしました

**Comment by moom1122** [comment]
@okadarenta さん、最終課題「FURIMA」の開発、お疲れ様です。
修正いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
